POST http://127.0.0.1:8000/api/signup HTTP/1.1
content-type: application/json

{
    "name":"rowen gonzales",
    "email": "growen@live.com",
    "password": "@gonzales101",
    "password_confirmation":"@gonzales101"
}

############
POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/json

{
    "email": "growen@live.com",
    "password": "@gonzales101",
    "confirmed_password":"@gonzales101"
}
